//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_LasBrumas.ServiceReference3 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transaccion", ReplyAction="http://tempuri.org/IService1/transaccionResponse")]
        string transaccion(string origin_account, string destiny_account, string detalle, float monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/transaccion", ReplyAction="http://tempuri.org/IService1/transaccionResponse")]
        System.Threading.Tasks.Task<string> transaccionAsync(string origin_account, string destiny_account, string detalle, float monto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Banco_LasBrumas.ServiceReference3.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Banco_LasBrumas.ServiceReference3.IService1>, Banco_LasBrumas.ServiceReference3.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string transaccion(string origin_account, string destiny_account, string detalle, float monto) {
            return base.Channel.transaccion(origin_account, destiny_account, detalle, monto);
        }
        
        public System.Threading.Tasks.Task<string> transaccionAsync(string origin_account, string destiny_account, string detalle, float monto) {
            return base.Channel.transaccionAsync(origin_account, destiny_account, detalle, monto);
        }
    }
}
