'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace servicio
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.sdde.bccr.fi.cr", ConfigurationName:="servicio.wsIndicadoresEconomicosSoap")>  _
    Public Interface wsIndicadoresEconomicosSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerIndicadoresEconomicos(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicos", ReplyAction:="*")>  _
        Function ObtenerIndicadoresEconomicosAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ObtenerIndicadoresEconomicosXML(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://ws.sdde.bccr.fi.cr/ObtenerIndicadoresEconomicosXML", ReplyAction:="*")>  _
        Function ObtenerIndicadoresEconomicosXMLAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface wsIndicadoresEconomicosSoapChannel
        Inherits servicio.wsIndicadoresEconomicosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class wsIndicadoresEconomicosSoapClient
        Inherits System.ServiceModel.ClientBase(Of servicio.wsIndicadoresEconomicosSoap)
        Implements servicio.wsIndicadoresEconomicosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function ObtenerIndicadoresEconomicos(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Data.DataSet Implements servicio.wsIndicadoresEconomicosSoap.ObtenerIndicadoresEconomicos
            Return MyBase.Channel.ObtenerIndicadoresEconomicos(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles)
        End Function
        
        Public Function ObtenerIndicadoresEconomicosAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements servicio.wsIndicadoresEconomicosSoap.ObtenerIndicadoresEconomicosAsync
            Return MyBase.Channel.ObtenerIndicadoresEconomicosAsync(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles)
        End Function
        
        Public Function ObtenerIndicadoresEconomicosXML(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As String Implements servicio.wsIndicadoresEconomicosSoap.ObtenerIndicadoresEconomicosXML
            Return MyBase.Channel.ObtenerIndicadoresEconomicosXML(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles)
        End Function
        
        Public Function ObtenerIndicadoresEconomicosXMLAsync(ByVal tcIndicador As String, ByVal tcFechaInicio As String, ByVal tcFechaFinal As String, ByVal tcNombre As String, ByVal tnSubNiveles As String) As System.Threading.Tasks.Task(Of String) Implements servicio.wsIndicadoresEconomicosSoap.ObtenerIndicadoresEconomicosXMLAsync
            Return MyBase.Channel.ObtenerIndicadoresEconomicosXMLAsync(tcIndicador, tcFechaInicio, tcFechaFinal, tcNombre, tnSubNiveles)
        End Function
    End Class
End Namespace
